# Generated by Django 5.1.15 on 2026-10-05 04:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedpost',
            name='media_type',
            field=models.CharField(choices=[('NONE', 'None'), ('IMAGE', 'Image'), ('VIDEO', 'Video')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='feedpost',
            name='media_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='feedpost',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='feedpost',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='feedpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feedpost',
            name='xp_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='post_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('WORKOUT', 'Workout'), ('RUN', 'Run'), ('PERSONAL_RECORD', 'Personal Record'), ('STREAK', 'Streak'), ('RANK_PROMOTION', 'Rank Promotion'), ('MILESTONE', 'Milestone')], default='WORKOUT', max_length=50),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('SPAM', 'Spam'), ('HARASSMENT', 'Harassment'), ('INAPPROPRIATE', 'Inappropriate Content'), ('HATE_ABUSIVE', 'Hate or Abusive Content'), ('MISLEADING', 'Misleading Information'), ('OTHER', 'Other')], default='SPAM', max_length=50)),
                ('details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='social.feedpost')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
