# Generated by Django 5.1.15 on 2026-10-03 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Outdoor Run', max_length=200)),
                ('distance_meters', models.FloatField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('avg_pace_sec_km', models.PositiveIntegerField()),
                ('max_pace_sec_km', models.PositiveIntegerField(blank=True, null=True)),
                ('elevation_gain_meters', models.FloatField(default=0.0)),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True)),
                ('polyline', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RunPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('sequence_order', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='runs.run')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='RunSplit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('split_number', models.PositiveSmallIntegerField()),
                ('distance_meters', models.FloatField(default=1000.0)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('pace_sec_km', models.PositiveIntegerField()),
                ('elevation_change', models.FloatField(default=0.0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='runs.run')),
            ],
            options={
                'ordering': ['split_number'],
            },
        ),
    ]
