# Generated by Django 5.1.15 on 2026-10-03 08:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('type', models.CharField(choices=[('GYM', 'Gym'), ('CALISTHENICS', 'Calisthenics')], db_index=True, max_length=20)),
                ('primary_muscle', models.CharField(choices=[('CHEST', 'Chest'), ('BACK', 'Back'), ('LEGS', 'Legs'), ('SHOULDERS', 'Shoulders'), ('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('CORE', 'Core'), ('GLUTES', 'Glutes'), ('FULL_BODY', 'Full Body')], db_index=True, max_length=20)),
                ('secondary_muscles', models.JSONField(blank=True, default=list)),
                ('muscle_groups', models.JSONField(blank=True, default=list)),
                ('equipment', models.JSONField(blank=True, default=list)),
                ('instructions', models.JSONField(blank=True, default=list)),
                ('form_tips', models.JSONField(blank=True, default=list)),
                ('common_mistakes', models.JSONField(blank=True, default=list)),
                ('media_url', models.URLField(blank=True, max_length=500, null=True)),
                ('easier_variation_id', models.UUIDField(blank=True, null=True)),
                ('harder_variation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
