# Generated by Django 5.1.15 on 2026-10-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='animation_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='breathing',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='INTERMEDIATE', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_media_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='media_source',
            field=models.CharField(blank=True, default='NATIVE_VECTOR', max_length=100),
        ),
        migrations.AddField(
            model_name='exercise',
            name='media_type',
            field=models.CharField(choices=[('ANIMATION', 'Animation'), ('VECTOR', 'Vector Animation'), ('VIDEO', 'Video'), ('GIF', 'GIF'), ('MODEL3D', '3D Model'), ('IMAGE', 'Static Image')], default='ANIMATION', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
