# Generated by Django 5.1.15 on 2026-10-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_animation_url_exercise_breathing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='overview',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='exercise',
            name='variations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
