# Generated by Django 5.1.15 on 2026-10-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='category',
            field=models.CharField(blank=True, default='Custom Routine', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='target_duration',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='target_weight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
