import datetime
from django.core.management.base import BaseCommand
from apps.authentication.models import User, UserProfile
from apps.exercises.models import Exercise, ExerciseType, MuscleGroup, DifficultyLevel, MediaType
from apps.progressions.models import ExerciseProgression, UserProgressionState, SkillBranch
from apps.workouts.models import Routine, RoutineExercise, WorkoutSession, WorkoutSet, PersonalRecord

class Command(BaseCommand):
    help = 'Seed database with 66+ exercises, 5 progression trees, and demo athlete data'

    def handle(self, *args, **kwargs):
        self.stdout.write('Clearing existing records...')
        WorkoutSet.objects.all().delete()
        WorkoutSession.objects.all().delete()
        PersonalRecord.objects.all().delete()
        RoutineExercise.objects.all().delete()
        Routine.objects.all().delete()
        UserProgressionState.objects.all().delete()
        ExerciseProgression.objects.all().delete()
        Exercise.objects.all().delete()
        UserProfile.objects.all().delete()
        User.objects.all().delete()

        self.stdout.write('Seeding 66 exercises...')
        exercises_data = [
            # CHEST
            {
                'name': 'Barbell Bench Press',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.CHEST,
                'secondary_muscles': [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
                'muscle_groups': [MuscleGroup.CHEST, MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
                'equipment': ['Barbell', 'Flat Bench'],
                'instructions': ['Lie flat on the bench with eyes directly under bar.', 'Grip bar shoulder-width.', 'Lower to mid-chest.', 'Drive up through heels.'],
                'form_tips': ['Keep feet planted', 'Retract scapula into bench', 'Maintain slight arch'],
                'common_mistakes': ['Flaring elbows 90 degrees', 'Bouncing bar off sternum'],
            },
            {
                'name': 'Incline Dumbbell Press',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.CHEST,
                'secondary_muscles': [MuscleGroup.SHOULDERS, MuscleGroup.TRICEPS],
                'muscle_groups': [MuscleGroup.CHEST, MuscleGroup.SHOULDERS, MuscleGroup.TRICEPS],
                'equipment': ['Dumbbells', 'Incline Bench'],
                'instructions': ['Set bench to 30 degrees.', 'Press dumbbells upward over chest.', 'Lower under control.'],
                'form_tips': ['Keep wrists neutral', 'Lower with 2-second eccentric cadence'],
                'common_mistakes': ['Incline angle too steep (>45 deg)'],
            },
            {
                'name': 'Lever Pec Deck Fly',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.CHEST,
                'secondary_muscles': [MuscleGroup.SHOULDERS],
                'muscle_groups': [MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
                'equipment': ['Leverage Machine'],
                'difficulty': DifficultyLevel.INTERMEDIATE,
                'overview': "The Lever Pec Deck Fly is a strength-building exercise targeting the chest muscles, particularly the pectoralis major. It's ideal for individuals at an intermediate fitness level who want to improve their upper body strength and muscle definition.",
                'instructions': [
                    'Sit on the pec deck machine with your back firmly against the pad and place your forearms on the padded levers, ensuring elbows and shoulders are aligned.',
                    'Push the levers together slowly, focusing on squeezing your chest muscles, until your hands meet in front of your chest.',
                    'Hold this position for a second to maximize contraction of the chest muscles.',
                    'Slowly return to the starting position, allowing your chest to stretch, and repeat for the desired reps.',
                ],
                'form_tips': [
                    'Controlled Movements: Avoid using momentum to lift heavier weights. Focus on slow, controlled reps to properly target the pectorals.',
                    'Full Range of Motion: Bring handles together until they touch, then return until chest is fully stretched. Avoid stopping early or overextending.',
                    'Proper Breathing: Exhale as you bring the handles together and inhale as you return.',
                ],
                'breathing': 'Exhale as you bring the handles together into peak contraction; inhale as you slowly return to the stretch position.',
                'common_mistakes': [
                    'Letting elbows drop below shoulder line.',
                    'Arching back off the pad during peak squeeze.',
                    'Using momentum or bouncing weights at the stretch point.',
                ],
                'variations': [
                    'Cable Crossover: Uses a cable machine for constant tension on the pectorals.',
                    'Resistance Band Chest Fly: Mimics the motion with bands, adding flexibility in workout location and intensity.',
                    'Incline Dumbbell Fly: Performed on an incline bench, targeting the upper chest muscles more than the standard fly.',
                    'Standing Cable Fly: Done standing with cables, targeting the chest from a different angle.',
                ],
                'video_url': '/videos/lever_pec_deck_fly.mp4',
                'thumbnail_url': 'https://ucarecdn.com/62571454-fff7-4344-8d23-820350d749c8/chest_fly_image.png',
                'media_url': '/videos/lever_pec_deck_fly.mp4',
                'media_type': MediaType.VIDEO,
                'media_source': 'exercisedb',
            },
            {
                'name': 'Cable Chest Fly',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.CHEST,
                'secondary_muscles': [MuscleGroup.SHOULDERS],
                'muscle_groups': [MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
                'equipment': ['Cable Machine'],
                'instructions': ['Set pulleys at chest height.', 'Bring hands together in hugging arc.', 'Squeeze chest at peak.'],
                'form_tips': ['Slight elbow bend', 'Focus on bringing inner biceps together'],
                'common_mistakes': ['Turning fly into press'],
            },
            {
                'name': 'Dumbbell Pullover',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.CHEST,
                'secondary_muscles': [MuscleGroup.BACK, MuscleGroup.TRICEPS],
                'muscle_groups': [MuscleGroup.CHEST, MuscleGroup.BACK, MuscleGroup.TRICEPS],
                'equipment': ['Dumbbell', 'Flat Bench'],
                'instructions': ['Lie across flat bench.', 'Lower dumbbell in arc behind head.', 'Pull back over chest using lats and chest.'],
                'form_tips': ['Slight elbow bend', 'Breathe deeply at bottom stretch'],
                'common_mistakes': ['Excessive elbow bend'],
            },
            # Push Progressions
            {
                'name': 'Wall Push-up',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.CHEST,
                'secondary_muscles': [MuscleGroup.TRICEPS, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.CHEST, MuscleGroup.TRICEPS, MuscleGroup.CORE],
                'equipment': ['Bodyweight', 'Wall'],
                'instructions': ['Stand facing wall at arms length.', 'Lower chest to wall.', 'Press back out.'],
                'form_tips': ['Keep core rigid', 'Do not shrug shoulders'],
                'common_mistakes': ['Hips sagging'],
                'prog_skill': SkillBranch.PUSH, 'prog_level': 1, 'unlock_criteria': '3 sets of 20 clean reps',
                'target_sets': 3, 'target_reps': 20,
            },
            {
                'name': 'Incline Push-up',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.CHEST,
                'secondary_muscles': [MuscleGroup.TRICEPS, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.CHEST, MuscleGroup.TRICEPS, MuscleGroup.CORE],
                'equipment': ['Bodyweight', 'Bench'],
                'instructions': ['Hands on bench, body straight.', 'Lower chest to edge.', 'Press up.'],
                'form_tips': ['Elbows at 45 degrees', 'Squeeze glutes'],
                'common_mistakes': ['Sagging back'],
                'prog_skill': SkillBranch.PUSH, 'prog_level': 2, 'unlock_criteria': '3 sets of 15 clean reps',
                'target_sets': 3, 'target_reps': 15,
            },
            {
                'name': 'Knee Push-up',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.CHEST,
                'secondary_muscles': [MuscleGroup.TRICEPS, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.CHEST, MuscleGroup.TRICEPS, MuscleGroup.CORE],
                'equipment': ['Bodyweight', 'Mat'],
                'instructions': ['Hands and knees on floor.', 'Lower chest to ground.', 'Press up.'],
                'form_tips': ['Hips in line with shoulders'],
                'common_mistakes': ['Butt sticking up'],
                'prog_skill': SkillBranch.PUSH, 'prog_level': 3, 'unlock_criteria': '3 sets of 12 clean reps',
                'target_sets': 3, 'target_reps': 12,
            },
            {
                'name': 'Standard Push-up',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.CHEST,
                'secondary_muscles': [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.CHEST, MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS, MuscleGroup.CORE],
                'equipment': ['Bodyweight'],
                'instructions': ['Hands shoulder-width, plank body.', 'Lower until chest hovers off floor.', 'Press up.'],
                'form_tips': ['Full lockout at top', 'Total body tension'],
                'common_mistakes': ['Flaring elbows 90 deg', 'Sagging hips'],
                'prog_skill': SkillBranch.PUSH, 'prog_level': 4, 'unlock_criteria': '3 sets of 15 clean reps',
                'target_sets': 3, 'target_reps': 15,
            },
            {
                'name': 'Diamond Push-up',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.TRICEPS,
                'secondary_muscles': [MuscleGroup.CHEST, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.TRICEPS, MuscleGroup.CHEST, MuscleGroup.CORE],
                'equipment': ['Bodyweight'],
                'instructions': ['Thumbs and index fingers touching under center chest.', 'Lower chest to hands.', 'Press up.'],
                'form_tips': ['Tuck elbows to ribs'],
                'common_mistakes': ['Elbows flaring'],
                'prog_skill': SkillBranch.PUSH, 'prog_level': 5, 'unlock_criteria': '3 sets of 12 clean reps',
                'target_sets': 3, 'target_reps': 12,
            },
            {
                'name': 'Archer Push-up',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.CHEST,
                'secondary_muscles': [MuscleGroup.TRICEPS, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.CHEST, MuscleGroup.TRICEPS, MuscleGroup.CORE],
                'equipment': ['Bodyweight'],
                'instructions': ['Wide stance.', 'Lower to one side while assistant arm stays locked straight.', 'Press back to center.'],
                'form_tips': ['Keep core braced'],
                'common_mistakes': ['Bending assistant arm'],
                'prog_skill': SkillBranch.PUSH, 'prog_level': 6, 'unlock_criteria': '3 sets of 8 reps per side',
                'target_sets': 3, 'target_reps': 8,
            },
            {
                'name': 'One-Arm Push-up',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.CHEST,
                'secondary_muscles': [MuscleGroup.TRICEPS, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.CHEST, MuscleGroup.TRICEPS, MuscleGroup.CORE],
                'equipment': ['Bodyweight'],
                'instructions': ['Feet wide, one hand on floor.', 'Lower chest to hand while resisting torso twist.', 'Press to lockout.'],
                'form_tips': ['Squeeze working arm lat and opposite glute'],
                'common_mistakes': ['Excessive body rotation'],
                'prog_skill': SkillBranch.PUSH, 'prog_level': 7, 'unlock_criteria': 'Mastery achieved (3 sets of 5 reps)',
                'target_sets': 3, 'target_reps': 5,
            },

            # BACK
            {
                'name': 'Barbell Deadlift',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.BACK,
                'secondary_muscles': [MuscleGroup.LEGS, MuscleGroup.GLUTES, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.BACK, MuscleGroup.LEGS, MuscleGroup.GLUTES, MuscleGroup.CORE],
                'equipment': ['Barbell', 'Plates'],
                'instructions': ['Feet hip-width, bar over mid-foot.', 'Hinge hips, grip bar.', 'Drive floor away, lock out hips.'],
                'form_tips': ['Bar stays in contact with legs', 'Lats engaged'],
                'common_mistakes': ['Rounding lumbar spine'],
            },
            {
                'name': 'Bent-Over Barbell Row',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.BACK,
                'secondary_muscles': [MuscleGroup.BICEPS, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.BACK, MuscleGroup.BICEPS, MuscleGroup.CORE],
                'equipment': ['Barbell'],
                'instructions': ['Hinge at 45 degree angle.', 'Pull bar to lower ribcage.', 'Squeeze scapula.'],
                'form_tips': ['Pull with elbows', 'Neutral spine'],
                'common_mistakes': ['Yanking with torso'],
            },
            {
                'name': 'Lat Pulldown',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.BACK,
                'secondary_muscles': [MuscleGroup.BICEPS],
                'muscle_groups': [MuscleGroup.BACK, MuscleGroup.BICEPS],
                'equipment': ['Cable Machine', 'Wide Bar'],
                'instructions': ['Sit with knees under pad.', 'Pull bar down to upper chest.', 'Control return.'],
                'form_tips': ['Depress shoulder blades first'],
                'common_mistakes': ['Leaning back too far'],
            },
            {
                'name': 'Seated Cable Row',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.BACK,
                'secondary_muscles': [MuscleGroup.BICEPS],
                'muscle_groups': [MuscleGroup.BACK, MuscleGroup.BICEPS],
                'equipment': ['Cable Machine', 'V-Handle'],
                'instructions': ['Sit tall, pull handle to navel.', 'Drive elbows back.', 'Control return.'],
                'form_tips': ['Do not sway torso'],
                'common_mistakes': ['Rounding shoulders'],
            },
            # Pull Progressions
            {
                'name': 'Doorframe / Australian Row',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.BACK,
                'secondary_muscles': [MuscleGroup.BICEPS, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.BACK, MuscleGroup.BICEPS, MuscleGroup.CORE],
                'equipment': ['Bodyweight', 'Low Bar / Rings'],
                'instructions': ['Position under waist-height bar.', 'Pull chest to bar.', 'Lower under control.'],
                'form_tips': ['Rigid plank body'],
                'common_mistakes': ['Sagging hips'],
                'prog_skill': SkillBranch.PULL, 'prog_level': 1, 'unlock_criteria': '3 sets of 15 clean reps',
                'target_sets': 3, 'target_reps': 15,
            },
            {
                'name': 'Active Dead Hang',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.BACK,
                'secondary_muscles': [MuscleGroup.SHOULDERS, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.BACK, MuscleGroup.SHOULDERS, MuscleGroup.CORE],
                'equipment': ['Pull-up Bar'],
                'instructions': ['Hang from bar with overhand grip.', 'Pull shoulder blades down and back.', 'Hold.'],
                'form_tips': ['Active shoulders', 'Toes pointed'],
                'common_mistakes': ['Passive loose shoulders'],
                'prog_skill': SkillBranch.PULL, 'prog_level': 2, 'unlock_criteria': '3 sets of 45-second holds',
                'target_sets': 3, 'target_reps': 1, 'target_hold_sec': 45,
            },
            {
                'name': 'Negative Pull-up',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.BACK,
                'secondary_muscles': [MuscleGroup.BICEPS, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.BACK, MuscleGroup.BICEPS, MuscleGroup.CORE],
                'equipment': ['Pull-up Bar', 'Box'],
                'instructions': ['Jump to chin over bar.', 'Lower down over 5 full seconds.', 'Repeat.'],
                'form_tips': ['Resist all the way down'],
                'common_mistakes': ['Dropping quickly at bottom'],
                'prog_skill': SkillBranch.PULL, 'prog_level': 3, 'unlock_criteria': '3 sets of 6 controlled 5s negatives',
                'target_sets': 3, 'target_reps': 6,
            },
            {
                'name': 'Standard Pull-up',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.BACK,
                'secondary_muscles': [MuscleGroup.BICEPS, MuscleGroup.SHOULDERS, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.BACK, MuscleGroup.BICEPS, MuscleGroup.SHOULDERS, MuscleGroup.CORE],
                'equipment': ['Pull-up Bar'],
                'instructions': ['Dead hang overhand.', 'Pull elbows to ribs until chin clears bar.', 'Lower to dead hang.'],
                'form_tips': ['Hollow body position', 'No kipping'],
                'common_mistakes': ['Partial range of motion'],
                'prog_skill': SkillBranch.PULL, 'prog_level': 4, 'unlock_criteria': '3 sets of 8 strict reps',
                'target_sets': 3, 'target_reps': 8,
            },
            {
                'name': 'Archer Pull-up',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.BACK,
                'secondary_muscles': [MuscleGroup.BICEPS, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.BACK, MuscleGroup.BICEPS, MuscleGroup.CORE],
                'equipment': ['Pull-up Bar'],
                'instructions': ['Wide grip.', 'Pull to one hand, extending other arm out straight.', 'Lower to center.'],
                'form_tips': ['Assistant arm remains straight'],
                'common_mistakes': ['Swinging body'],
                'prog_skill': SkillBranch.PULL, 'prog_level': 5, 'unlock_criteria': '3 sets of 5 reps per side',
                'target_sets': 3, 'target_reps': 5,
            },
            {
                'name': 'Bar Muscle-up',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.BACK,
                'secondary_muscles': [MuscleGroup.TRICEPS, MuscleGroup.CHEST, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.BACK, MuscleGroup.TRICEPS, MuscleGroup.CHEST, MuscleGroup.CORE],
                'equipment': ['Pull-up Bar'],
                'instructions': ['Explosive pull toward waist.', 'Fast wrist transition over bar.', 'Press to lockout.'],
                'form_tips': ['Pull high before rotating wrists'],
                'common_mistakes': ['Chicken-winging one arm'],
                'prog_skill': SkillBranch.PULL, 'prog_level': 6, 'unlock_criteria': 'Mastery achieved (3 sets of 5 reps)',
                'target_sets': 3, 'target_reps': 5,
            },

            # LEGS
            {
                'name': 'Barbell Back Squat',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.LEGS,
                'secondary_muscles': [MuscleGroup.GLUTES, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.LEGS, MuscleGroup.GLUTES, MuscleGroup.CORE],
                'equipment': ['Barbell', 'Squat Rack'],
                'instructions': ['Bar across upper traps.', 'Descend until hip crease is below knee.', 'Drive up through midfoot.'],
                'form_tips': ['Knees track over toes', 'Core braced'],
                'common_mistakes': ['Knees caving in', 'Rising on toes'],
            },
            {
                'name': 'Romanian Deadlift (RDL)',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.LEGS,
                'secondary_muscles': [MuscleGroup.GLUTES, MuscleGroup.BACK],
                'muscle_groups': [MuscleGroup.LEGS, MuscleGroup.GLUTES, MuscleGroup.BACK],
                'equipment': ['Barbell', 'Dumbbells'],
                'instructions': ['Hinge hips back with soft knees.', 'Lower bar along shins until hamstring stretch.', 'Drive hips forward.'],
                'form_tips': ['Think hips back, not bending over'],
                'common_mistakes': ['Rounding spine'],
            },
            {
                'name': 'Leg Press',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.LEGS,
                'secondary_muscles': [MuscleGroup.GLUTES],
                'muscle_groups': [MuscleGroup.LEGS, MuscleGroup.GLUTES],
                'equipment': ['Leg Press Machine'],
                'instructions': ['Feet hip-width on sled.', 'Lower until knees at 90 deg.', 'Press up smoothly.'],
                'form_tips': ['Never hyper-lock knees violently'],
                'common_mistakes': ['Lowering too deep causing pelvic tuck'],
            },
            {
                'name': 'Walking Dumbbell Lunge',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.LEGS,
                'secondary_muscles': [MuscleGroup.GLUTES, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.LEGS, MuscleGroup.GLUTES, MuscleGroup.CORE],
                'equipment': ['Dumbbells'],
                'instructions': ['Step forward, lower back knee near floor.', 'Drive through front heel and step through.'],
                'form_tips': ['Torso tall with slight forward lean'],
                'common_mistakes': ['Front knee caving in'],
            },
            # Legs Progressions
            {
                'name': 'Assisted Air Squat',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.LEGS,
                'secondary_muscles': [MuscleGroup.GLUTES],
                'muscle_groups': [MuscleGroup.LEGS, MuscleGroup.GLUTES],
                'equipment': ['Bodyweight', 'Pole'],
                'instructions': ['Hold upright pole at chest.', 'Squat down below parallel.', 'Stand up.'],
                'form_tips': ['Use minimal arm pulling'],
                'common_mistakes': ['Heels coming off ground'],
                'prog_skill': SkillBranch.LEGS, 'prog_level': 1, 'unlock_criteria': '3 sets of 20 clean reps',
                'target_sets': 3, 'target_reps': 20,
            },
            {
                'name': 'Bodyweight Air Squat',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.LEGS,
                'secondary_muscles': [MuscleGroup.GLUTES, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.LEGS, MuscleGroup.GLUTES, MuscleGroup.CORE],
                'equipment': ['Bodyweight'],
                'instructions': ['Feet shoulder-width.', 'Descend below parallel.', 'Stand tall.'],
                'form_tips': ['Tripod foot pressure'],
                'common_mistakes': ['Cutting depth'],
                'prog_skill': SkillBranch.LEGS, 'prog_level': 2, 'unlock_criteria': '3 sets of 30 clean reps',
                'target_sets': 3, 'target_reps': 30,
            },
            {
                'name': 'Bulgarian Split Squat',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.LEGS,
                'secondary_muscles': [MuscleGroup.GLUTES, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.LEGS, MuscleGroup.GLUTES, MuscleGroup.CORE],
                'equipment': ['Bodyweight', 'Bench'],
                'instructions': ['Back foot elevated on bench.', 'Lower hips until lead thigh parallel.', 'Drive through front heel.'],
                'form_tips': ['Lead leg takes 85% of weight'],
                'common_mistakes': ['Pushing off back foot'],
                'prog_skill': SkillBranch.LEGS, 'prog_level': 3, 'unlock_criteria': '3 sets of 15 reps per leg',
                'target_sets': 3, 'target_reps': 15,
            },
            {
                'name': 'Box Assisted Pistol Squat',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.LEGS,
                'secondary_muscles': [MuscleGroup.GLUTES, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.LEGS, MuscleGroup.GLUTES, MuscleGroup.CORE],
                'equipment': ['Bodyweight', 'Box'],
                'instructions': ['Stand single-legged on box.', 'Squat down on working leg.', 'Press to stand.'],
                'form_tips': ['Align knee with second toe'],
                'common_mistakes': ['Dropping without control'],
                'prog_skill': SkillBranch.LEGS, 'prog_level': 4, 'unlock_criteria': '3 sets of 10 reps per leg',
                'target_sets': 3, 'target_reps': 10,
            },
            {
                'name': 'Strict Pistol Squat',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.LEGS,
                'secondary_muscles': [MuscleGroup.GLUTES, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.LEGS, MuscleGroup.GLUTES, MuscleGroup.CORE],
                'equipment': ['Bodyweight'],
                'instructions': ['Balance on one leg, extend other straight out.', 'Squat deep.', 'Drive back up.'],
                'form_tips': ['Ankle mobility and quad tension'],
                'common_mistakes': ['Forward heel lifting'],
                'prog_skill': SkillBranch.LEGS, 'prog_level': 5, 'unlock_criteria': 'Mastery achieved (3 sets of 8 reps per leg)',
                'target_sets': 3, 'target_reps': 8,
            },

            # SHOULDERS
            {
                'name': 'Overhead Barbell Press (OHP)',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.SHOULDERS,
                'secondary_muscles': [MuscleGroup.TRICEPS, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.SHOULDERS, MuscleGroup.TRICEPS, MuscleGroup.CORE],
                'equipment': ['Barbell'],
                'instructions': ['Bar at clavicles.', 'Press straight overhead.', 'Push head forward at lockout.'],
                'form_tips': ['Squeeze glutes and abs'],
                'common_mistakes': ['Overarching lower back'],
            },
            {
                'name': 'Dumbbell Lateral Raise',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.SHOULDERS,
                'secondary_muscles': [MuscleGroup.BACK],
                'muscle_groups': [MuscleGroup.SHOULDERS, MuscleGroup.BACK],
                'equipment': ['Dumbbells'],
                'instructions': ['Raise dumbbells to sides up to shoulder level.', 'Lead with elbows.', 'Lower slowly.'],
                'form_tips': ['Push weights outward toward walls'],
                'common_mistakes': ['Swinging torso'],
            },
            {
                'name': 'Rear Delt Face Pull',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.SHOULDERS,
                'secondary_muscles': [MuscleGroup.BACK],
                'muscle_groups': [MuscleGroup.SHOULDERS, MuscleGroup.BACK],
                'equipment': ['Cable Machine', 'Rope'],
                'instructions': ['Pull rope to forehead.', 'Separate hands and rotate forearms up.'],
                'form_tips': ['Keep elbows high'],
                'common_mistakes': ['Pulling to chin'],
            },
            # Handstand Progressions
            {
                'name': 'Pike Push-up',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.SHOULDERS,
                'secondary_muscles': [MuscleGroup.TRICEPS, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.SHOULDERS, MuscleGroup.TRICEPS, MuscleGroup.CORE],
                'equipment': ['Bodyweight'],
                'instructions': ['Downward dog position.', 'Lower crown of head forward to touch floor.', 'Push back up.'],
                'form_tips': ['Hips high over shoulders'],
                'common_mistakes': ['Lowering head between hands instead of forward'],
                'prog_skill': SkillBranch.HANDSTAND, 'prog_level': 1, 'unlock_criteria': '3 sets of 12 clean reps',
                'target_sets': 3, 'target_reps': 12,
            },
            {
                'name': 'Elevated Feet Pike Push-up',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.SHOULDERS,
                'secondary_muscles': [MuscleGroup.TRICEPS, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.SHOULDERS, MuscleGroup.TRICEPS, MuscleGroup.CORE],
                'equipment': ['Bodyweight', 'Bench'],
                'instructions': ['Feet on bench.', 'Walk hands back until hips stack over shoulders.', 'Lower head forward, press up.'],
                'form_tips': ['Elbows at 45 degrees'],
                'common_mistakes': ['Hips drifting backwards'],
                'prog_skill': SkillBranch.HANDSTAND, 'prog_level': 2, 'unlock_criteria': '3 sets of 10 clean reps',
                'target_sets': 3, 'target_reps': 10,
            },
            {
                'name': 'Chest-to-Wall Handstand Hold',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.SHOULDERS,
                'secondary_muscles': [MuscleGroup.CORE, MuscleGroup.TRICEPS],
                'muscle_groups': [MuscleGroup.SHOULDERS, MuscleGroup.CORE, MuscleGroup.TRICEPS],
                'equipment': ['Bodyweight', 'Wall'],
                'instructions': ['Walk feet up wall until chest is near wall.', 'Push floor actively away.', 'Hold rigid body.'],
                'form_tips': ['Only toes and nose touch wall'],
                'common_mistakes': ['Banana back arch'],
                'prog_skill': SkillBranch.HANDSTAND, 'prog_level': 3, 'unlock_criteria': '3 sets of 45-second holds',
                'target_sets': 3, 'target_reps': 1, 'target_hold_sec': 45,
            },
            {
                'name': 'Freestanding Handstand Kick-up',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.SHOULDERS,
                'secondary_muscles': [MuscleGroup.CORE, MuscleGroup.TRICEPS],
                'muscle_groups': [MuscleGroup.SHOULDERS, MuscleGroup.CORE, MuscleGroup.TRICEPS],
                'equipment': ['Bodyweight'],
                'instructions': ['Kick up into balance.', 'Use fingertip claw pressure to correct balance.', 'Hold.'],
                'form_tips': ['Grip ground like claws'],
                'common_mistakes': ['Over-kicking'],
                'prog_skill': SkillBranch.HANDSTAND, 'prog_level': 4, 'unlock_criteria': '3 holds of 15+ seconds',
                'target_sets': 3, 'target_reps': 1, 'target_hold_sec': 15,
            },
            {
                'name': 'Handstand Push-up (HSPU)',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.SHOULDERS,
                'secondary_muscles': [MuscleGroup.TRICEPS, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.SHOULDERS, MuscleGroup.TRICEPS, MuscleGroup.CORE],
                'equipment': ['Bodyweight', 'Wall'],
                'instructions': ['In handstand against wall.', 'Lower head forward into tripod.', 'Press to full lockout.'],
                'form_tips': ['Maintain hollow tension'],
                'common_mistakes': ['Kipping or arching spine'],
                'prog_skill': SkillBranch.HANDSTAND, 'prog_level': 5, 'unlock_criteria': 'Mastery achieved (3 sets of 5 reps)',
                'target_sets': 3, 'target_reps': 5,
            },

            # ARMS (Biceps & Triceps)
            {
                'name': 'Barbell Bicep Curl',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.BICEPS,
                'secondary_muscles': [MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.BICEPS, MuscleGroup.CORE],
                'equipment': ['Barbell'],
                'instructions': ['Stand tall, curl bar toward shoulders.', 'Elbows pinned to ribs.', 'Lower over 2 seconds.'],
                'form_tips': ['Wrists neutral'],
                'common_mistakes': ['Swinging hips'],
            },
            {
                'name': 'Incline Dumbbell Curl',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.BICEPS,
                'secondary_muscles': [],
                'muscle_groups': [MuscleGroup.BICEPS],
                'equipment': ['Dumbbells', 'Incline Bench'],
                'instructions': ['Sit on 45-deg bench.', 'Curl dumbbells without moving upper arm forward.'],
                'form_tips': ['Deep bottom stretch'],
                'common_mistakes': ['Lifting shoulders off bench'],
            },
            {
                'name': 'Chin-up',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.BICEPS,
                'secondary_muscles': [MuscleGroup.BACK, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.BICEPS, MuscleGroup.BACK, MuscleGroup.CORE],
                'equipment': ['Pull-up Bar'],
                'instructions': ['Underhand palms-facing grip.', 'Pull chin over bar.', 'Lower to full hang.'],
                'form_tips': ['Drive elbows down'],
                'common_mistakes': ['Half reps'],
            },
            {
                'name': 'Tricep Cable Pushdown',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.TRICEPS,
                'secondary_muscles': [],
                'muscle_groups': [MuscleGroup.TRICEPS],
                'equipment': ['Cable Machine', 'Rope'],
                'instructions': ['Pin elbows to ribs.', 'Push rope down, spreading ends at bottom.'],
                'form_tips': ['Stationary elbows'],
                'common_mistakes': ['Using shoulder momentum'],
            },
            {
                'name': 'Skull Crusher (Lying Extension)',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.TRICEPS,
                'secondary_muscles': [],
                'muscle_groups': [MuscleGroup.TRICEPS],
                'equipment': ['EZ Bar', 'Bench'],
                'instructions': ['Lie flat.', 'Lower bar to hairline bending only elbows.', 'Extend to lockout.'],
                'form_tips': ['Upper arms angled slightly back'],
                'common_mistakes': ['Elbows flaring wide'],
            },
            {
                'name': 'Parallel Bar Dips',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.TRICEPS,
                'secondary_muscles': [MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
                'muscle_groups': [MuscleGroup.TRICEPS, MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
                'equipment': ['Dip Bars'],
                'instructions': ['Support on bars.', 'Lower until shoulders reach 90 degrees.', 'Press to lockout.'],
                'form_tips': ['Lean slightly forward'],
                'common_mistakes': ['Cutting depth short'],
            },

            # CORE
            {
                'name': 'Cable Woodchopper',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.CORE,
                'secondary_muscles': [MuscleGroup.SHOULDERS],
                'muscle_groups': [MuscleGroup.CORE, MuscleGroup.SHOULDERS],
                'equipment': ['Cable Machine'],
                'instructions': ['Rotate torso diagonally across body.', 'Control return.'],
                'form_tips': ['Pivot back foot'],
                'common_mistakes': ['Pulling only with arms'],
            },
            {
                'name': 'Ab Wheel Rollout',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.CORE,
                'secondary_muscles': [MuscleGroup.BACK],
                'muscle_groups': [MuscleGroup.CORE, MuscleGroup.BACK],
                'equipment': ['Ab Wheel', 'Mat'],
                'instructions': ['Kneel on mat.', 'Roll wheel forward into hollow plank.', 'Pull back with abs and lats.'],
                'form_tips': ['Posterior pelvic tilt'],
                'common_mistakes': ['Lower back sagging'],
            },
            # Core Progressions
            {
                'name': 'Deadbug Hold & Extension',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.CORE,
                'secondary_muscles': [],
                'muscle_groups': [MuscleGroup.CORE],
                'equipment': ['Bodyweight', 'Mat'],
                'instructions': ['Lower back flat on floor.', 'Extend opposite arm and leg.', 'Return and alternate.'],
                'form_tips': ['Zero lower back arch'],
                'common_mistakes': ['Moving too fast'],
                'prog_skill': SkillBranch.CORE, 'prog_level': 1, 'unlock_criteria': '3 sets of 20 alternating reps',
                'target_sets': 3, 'target_reps': 20,
            },
            {
                'name': 'Hollow Body Hold',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.CORE,
                'secondary_muscles': [MuscleGroup.LEGS],
                'muscle_groups': [MuscleGroup.CORE, MuscleGroup.LEGS],
                'equipment': ['Bodyweight'],
                'instructions': ['Press spine into floor.', 'Elevate shoulders and legs into banana shape.', 'Hold.'],
                'form_tips': ['Spine glued to floor'],
                'common_mistakes': ['Arching lumbar'],
                'prog_skill': SkillBranch.CORE, 'prog_level': 2, 'unlock_criteria': '3 sets of 45-second holds',
                'target_sets': 3, 'target_reps': 1, 'target_hold_sec': 45,
            },
            {
                'name': 'Hanging Knee Raises',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.CORE,
                'secondary_muscles': [MuscleGroup.BACK],
                'muscle_groups': [MuscleGroup.CORE, MuscleGroup.BACK],
                'equipment': ['Pull-up Bar'],
                'instructions': ['Hang from bar.', 'Curl pelvis and pull knees to chest without swinging.'],
                'form_tips': ['Posterior pelvic tilt at top'],
                'common_mistakes': ['Swinging momentum'],
                'prog_skill': SkillBranch.CORE, 'prog_level': 3, 'unlock_criteria': '3 sets of 15 clean reps',
                'target_sets': 3, 'target_reps': 15,
            },
            {
                'name': 'Hanging Strict Toes-to-Bar',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.CORE,
                'secondary_muscles': [MuscleGroup.BACK, MuscleGroup.LEGS],
                'muscle_groups': [MuscleGroup.CORE, MuscleGroup.BACK, MuscleGroup.LEGS],
                'equipment': ['Pull-up Bar'],
                'instructions': ['Legs straight, toes pointed.', 'Pull lats and compress abs to touch toes to bar.'],
                'form_tips': ['No kipping'],
                'common_mistakes': ['Bending knees on descent'],
                'prog_skill': SkillBranch.CORE, 'prog_level': 4, 'unlock_criteria': '3 sets of 10 strict reps',
                'target_sets': 3, 'target_reps': 10,
            },
            {
                'name': 'L-Sit Hold',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.CORE,
                'secondary_muscles': [MuscleGroup.TRICEPS, MuscleGroup.LEGS],
                'muscle_groups': [MuscleGroup.CORE, MuscleGroup.TRICEPS, MuscleGroup.LEGS],
                'equipment': ['Parallettes / Floor'],
                'instructions': ['Support with arms locked.', 'Raise straight legs parallel to ground.', 'Hold.'],
                'form_tips': ['Push floor away'],
                'common_mistakes': ['Dropping legs below 90 deg'],
                'prog_skill': SkillBranch.CORE, 'prog_level': 5, 'unlock_criteria': '3 sets of 20-second holds',
                'target_sets': 3, 'target_reps': 1, 'target_hold_sec': 20,
            },
            {
                'name': 'Dragon Flag',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.CORE,
                'secondary_muscles': [MuscleGroup.BACK, MuscleGroup.GLUTES],
                'muscle_groups': [MuscleGroup.CORE, MuscleGroup.BACK, MuscleGroup.GLUTES],
                'equipment': ['Bench'],
                'instructions': ['Lie on bench, grip edge behind head.', 'Lift entire body straight into air.', 'Lower slowly without breaking at hips.'],
                'form_tips': ['Body rigid like wood'],
                'common_mistakes': ['Bending hips'],
                'prog_skill': SkillBranch.CORE, 'prog_level': 6, 'unlock_criteria': 'Mastery achieved (3 sets of 6 strict reps)',
                'target_sets': 3, 'target_reps': 6,
            },

            # GLUTES
            {
                'name': 'Barbell Hip Thrust',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.GLUTES,
                'secondary_muscles': [MuscleGroup.LEGS, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.GLUTES, MuscleGroup.LEGS, MuscleGroup.CORE],
                'equipment': ['Barbell', 'Bench'],
                'instructions': ['Upper back on bench, bar over hips.', 'Drive through heels to full extension.', 'Squeeze glutes 1 sec.'],
                'form_tips': ['Chin tucked forward'],
                'common_mistakes': ['Hyperextending lower back'],
            },
            {
                'name': 'Cable Glute Kickback',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.GLUTES,
                'secondary_muscles': [MuscleGroup.LEGS],
                'muscle_groups': [MuscleGroup.GLUTES, MuscleGroup.LEGS],
                'equipment': ['Cable Machine', 'Ankle Strap'],
                'instructions': ['Kick leg straight back.', 'Squeeze glute at peak.'],
                'form_tips': ['Torso steady'],
                'common_mistakes': ['Swinging wildly'],
            },
            {
                'name': 'Single-Leg Glute Bridge',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.GLUTES,
                'secondary_muscles': [MuscleGroup.LEGS, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.GLUTES, MuscleGroup.LEGS, MuscleGroup.CORE],
                'equipment': ['Bodyweight', 'Mat'],
                'instructions': ['One leg extended.', 'Drive through working heel to lift hips.'],
                'form_tips': ['Pelvis stays level'],
                'common_mistakes': ['Pelvis dipping to side'],
            },

            # FULL BODY
            {
                'name': 'Barbell Clean and Press',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.FULL_BODY,
                'secondary_muscles': [MuscleGroup.SHOULDERS, MuscleGroup.LEGS, MuscleGroup.BACK],
                'muscle_groups': [MuscleGroup.FULL_BODY, MuscleGroup.SHOULDERS, MuscleGroup.LEGS, MuscleGroup.BACK],
                'equipment': ['Barbell'],
                'instructions': ['Clean bar to front rack.', 'Drive through legs and press overhead.'],
                'form_tips': ['Triple extension from floor'],
                'common_mistakes': ['Pulling only with arms'],
            },
            {
                'name': 'Kettlebell Swing',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.FULL_BODY,
                'secondary_muscles': [MuscleGroup.GLUTES, MuscleGroup.BACK, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.FULL_BODY, MuscleGroup.GLUTES, MuscleGroup.BACK, MuscleGroup.CORE],
                'equipment': ['Kettlebell'],
                'instructions': ['Hike kettlebell back in hip hinge.', 'Snap hips forward explosively.'],
                'form_tips': ['Power from glutes, not shoulders'],
                'common_mistakes': ['Squatting instead of hinging'],
            },
            {
                'name': 'Burpee with Push-up',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.FULL_BODY,
                'secondary_muscles': [MuscleGroup.CHEST, MuscleGroup.LEGS, MuscleGroup.CORE],
                'muscle_groups': [MuscleGroup.FULL_BODY, MuscleGroup.CHEST, MuscleGroup.LEGS, MuscleGroup.CORE],
                'equipment': ['Bodyweight'],
                'instructions': ['Drop to floor, perform push-up, jump back up with hands overhead.'],
                'form_tips': ['Land softly'],
                'common_mistakes': ['Sagging back in plank'],
            },
            {
                'name': 'Bear Crawl',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.FULL_BODY,
                'secondary_muscles': [MuscleGroup.CORE, MuscleGroup.SHOULDERS, MuscleGroup.LEGS],
                'muscle_groups': [MuscleGroup.FULL_BODY, MuscleGroup.CORE, MuscleGroup.SHOULDERS, MuscleGroup.LEGS],
                'equipment': ['Bodyweight'],
                'instructions': ['Hands under shoulders, knees hovering 2 inches off floor.', 'Crawl with opposite limbs.'],
                'form_tips': ['Keep back flat and hips level'],
                'common_mistakes': ['Piking hips up'],
            },
            {
                'name': 'Farmer Walk',
                'type': ExerciseType.GYM,
                'primary_muscle': MuscleGroup.FULL_BODY,
                'secondary_muscles': [MuscleGroup.BACK, MuscleGroup.CORE, MuscleGroup.LEGS],
                'muscle_groups': [MuscleGroup.FULL_BODY, MuscleGroup.BACK, MuscleGroup.CORE, MuscleGroup.LEGS],
                'equipment': ['Heavy Dumbbells'],
                'instructions': ['Hold heavy weights at sides.', 'Walk tall with deliberate strides.'],
                'form_tips': ['Shoulders pinned back'],
                'common_mistakes': ['Slouching forward'],
            },
            {
                'name': 'Mountain Climbers',
                'type': ExerciseType.CALISTHENICS,
                'primary_muscle': MuscleGroup.FULL_BODY,
                'secondary_muscles': [MuscleGroup.CORE, MuscleGroup.SHOULDERS, MuscleGroup.LEGS],
                'muscle_groups': [MuscleGroup.FULL_BODY, MuscleGroup.CORE, MuscleGroup.SHOULDERS, MuscleGroup.LEGS],
                'equipment': ['Bodyweight'],
                'instructions': ['In high plank, drive knees forward rhythmically.'],
                'form_tips': ['Hips level with shoulders'],
                'common_mistakes': ['Bouncing hips up and down'],
            },
        ]

        created_map = {}
        for ex in exercises_data:
            skill = ex.pop('prog_skill', None)
            level = ex.pop('prog_level', None)
            criteria = ex.pop('unlock_criteria', None)
            t_sets = ex.pop('target_sets', 3)
            t_reps = ex.pop('target_reps', 10)
            t_hold = ex.pop('target_hold_sec', None)

            record = Exercise.objects.create(**ex)
            created_map[record.name] = record

            if skill and level:
                ExerciseProgression.objects.create(
                    skill=skill,
                    level=level,
                    exercise=record,
                    unlock_criteria=criteria or 'Complete target',
                    target_sets=t_sets,
                    target_reps=t_reps,
                    target_hold_sec=t_hold,
                )

        self.stdout.write('Creating demo user (demo@fittrack.app)...')
        demo_user = User.objects.create_user(email='demo@fittrack.app', password='Password123!')
        UserProfile.objects.create(
            user=demo_user,
            display_name='Demo Athlete',
            units='METRIC',
            experience_level='INTERMEDIATE',
            fitness_goal='Muscle Gain & Calisthenics Mastery',
            days_per_week=4,
            equipment=['Dumbbells', 'Barbell', 'Pull-up Bar'],
        )

        for skill, current_lvl in [('PUSH', 4), ('PULL', 3), ('LEGS', 3), ('CORE', 3), ('HANDSTAND', 2)]:
            UserProgressionState.objects.create(user=demo_user, skill=skill, current_level=current_lvl)

        self.stdout.write('Creating demo routines...')
        push_routine = Routine.objects.create(
            user=demo_user,
            name='Push Day (Chest, Shoulders & Triceps)',
            description='Foundational upper body push session targeting hypertrophy.',
            is_public=True,
        )
        for i, (name, sets, reps, rest) in enumerate([
            ('Barbell Bench Press', 4, 8, 120),
            ('Overhead Barbell Press (OHP)', 3, 8, 90),
            ('Incline Dumbbell Press', 3, 10, 90),
            ('Parallel Bar Dips', 3, 12, 60),
        ], start=1):
            if name in created_map:
                RoutineExercise.objects.create(
                    routine=push_routine,
                    exercise=created_map[name],
                    order_index=i,
                    target_sets=sets,
                    target_reps=reps,
                    target_rest_sec=rest,
                )

        pull_routine = Routine.objects.create(
            user=demo_user,
            name='Pull Day (Back & Biceps)',
            description='Vertical and horizontal pulling session.',
            is_public=True,
        )
        for i, (name, sets, reps, rest) in enumerate([
            ('Barbell Deadlift', 3, 5, 180),
            ('Standard Pull-up', 4, 8, 90),
            ('Bent-Over Barbell Row', 3, 10, 90),
            ('Barbell Bicep Curl', 3, 12, 60),
        ], start=1):
            if name in created_map:
                RoutineExercise.objects.create(
                    routine=pull_routine,
                    exercise=created_map[name],
                    order_index=i,
                    target_sets=sets,
                    target_reps=reps,
                    target_rest_sec=rest,
                )

        self.stdout.write('Creating sample workout session and PR...')
        bench_ex = created_map.get('Barbell Bench Press')
        if bench_ex:
            session = WorkoutSession.objects.create(
                user=demo_user,
                routine=push_routine,
                name='Push Day',
                start_time=datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=2),
                end_time=datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=2, hours=-1),
                duration_seconds=3600,
                total_volume_kg=3240,
                is_completed=True,
            )
            for num, wt, rp in [(1, 80, 8), (2, 85, 8), (3, 90, 6), (4, 90, 5)]:
                WorkoutSet.objects.create(
                    session=session,
                    exercise=bench_ex,
                    set_number=num,
                    weight_kg=wt,
                    reps=rp,
                    is_completed=True,
                )

            PersonalRecord.objects.create(
                user=demo_user,
                exercise=bench_ex,
                type='MAX_WEIGHT',
                value=90.0,
                session_id=session.id,
            )

        self.stdout.write(self.style.SUCCESS('Successfully seeded database with 66 exercises, 5 progression trees, demo user, routines, and PR!'))
