# Generated by Django 5.1.15 on 2026-10-03 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseProgression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill', models.CharField(choices=[('PUSH', 'Push'), ('PULL', 'Pull'), ('LEGS', 'Legs'), ('CORE', 'Core'), ('HANDSTAND', 'Handstand')], db_index=True, max_length=20)),
                ('level', models.PositiveSmallIntegerField()),
                ('unlock_criteria', models.CharField(max_length=255)),
                ('target_sets', models.PositiveSmallIntegerField(default=3)),
                ('target_reps', models.PositiveSmallIntegerField(default=10)),
                ('target_hold_sec', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='exercises.exercise')),
            ],
            options={
                'ordering': ['skill', 'level'],
                'unique_together': {('skill', 'level')},
            },
        ),
        migrations.CreateModel(
            name='UserProgressionState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill', models.CharField(choices=[('PUSH', 'Push'), ('PULL', 'Pull'), ('LEGS', 'Legs'), ('CORE', 'Core'), ('HANDSTAND', 'Handstand')], max_length=20)),
                ('current_level', models.PositiveSmallIntegerField(default=1)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
